# Configuración del sitio
site_name: "Unidad2-TareaRA2-Joaquin"
site_description: "Documentación de la actividad de la Unidad 2"
site_author: "JBLeopard"
# Tema
theme:
  name: material
  language: es
  palette:
    primary: indigo
    accent: cyan
# Menú navegación
nav:
  - Inicio: index.md
  - Trazado de vulnerabiliad: TrazadoVulnerabilidadGoAnywhere.md
  - Análisis de vulnerabilidad en máquina vulnerable: analisisVulnerabilidad.md
  - Comprobación de los requisitos de Seguridad de una aplicación: ComprobacionRequisitosAplicacion.md
  - Reflexión sobre los riesgos de las aplicaciones: conclusiones.md
# Carpeta donde están los archivos Markdown
docs_dir: docs
# Extensions Markdown
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - codehilite
  - footnotes
  - def_list
