# Configuración del sitio
site_name: "Unidad1-TareaRA1-Joaquin"
site_description: "Documentación de la actividad de la Unidad 1"
site_author: "JBLeopard"
# Tema
theme:
  name: material
  language: es
  palette:
    primary: indigo
    accent: cyan
# Menú navegación
nav:
  - Inicio: index.md
  - Documentación y prueba del programa: documentacion.md
  - Realización de los test unitarios de la aplicación: tests.md
  - Ejecución de la aplicación en un entorno controlado: sandbox.md
  - Reflexión sobre comparación de la infraestructura de seguridad de los lenguajes: conclusiones.md
# Carpeta donde están los archivos Markdown
docs_dir: docs
# Extensions Markdown
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - codehilite
  - footnotes
  - def_list
